// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// commextr
List commextr(int d, int ps, NumericVector matrix, NumericVector res, int vb);
RcppExport SEXP _MODifieRDev_commextr(SEXP dSEXP, SEXP psSEXP, SEXP matrixSEXP, SEXP resSEXP, SEXP vbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type ps(psSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< int >::type vb(vbSEXP);
    rcpp_result_gen = Rcpp::wrap(commextr(d, ps, matrix, res, vb));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void complex(void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_MODifieRDev_commextr", (DL_FUNC) &_MODifieRDev_commextr, 5},
    {"complex", (DL_FUNC) &complex, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MODifieRDev(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
