# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

commextr <- function(d, ps, matrix, res, vb) {
    .Call('_MODifieRDev_commextr', PACKAGE = 'MODifieRDev', d, ps, matrix, res, vb)
}

